from io import BytesIO
from datetime import datetime, timezone

from openpyxl import Workbook
from openpyxl.styles import Font
from sqlalchemy.orm import Session

from app.models.class_ import Class
from app.models.leave import AlterAssignment, LeaveRequest
from app.models.timetable import TimetableSlot
from app.models.user import User


def _sheet(workbook: Workbook, title: str, headers: list[str]):
    ws = workbook.active if workbook.active.title == "Sheet" else workbook.create_sheet()
    ws.title = title
    ws.append(headers)
    for cell in ws[1]:
        cell.font = Font(bold=True)
    ws.freeze_panes = "A2"
    return ws


def build_master_export(db: Session, generated_by: str) -> bytes:
    wb = Workbook()
    ws = _sheet(wb, "Class Faculty Master", ["Class", "Section", "Semester", "Owning Department ID", "Teacher", "Teacher Department", "Subject", "Day Order", "Period", "Room"])
    rows = db.query(TimetableSlot).join(Class).join(User).order_by(Class.name, Class.section, TimetableSlot.day_order, TimetableSlot.period_number).all()
    for slot in rows:
        ws.append([slot.class_.name, slot.class_.section, slot.class_.semester, slot.class_.department_id, slot.teacher.name, slot.teacher.department, slot.subject.name if slot.subject else None, slot.day_order, slot.period_number, slot.room.room_number if slot.room else None])

    ws = _sheet(wb, "Substitution Accountability", ["Leave ID", "Date", "Class", "Absent Teacher", "Absent Department", "Substitute", "Substitute Department", "Cross Department", "Day Order", "Period", "Assignment Type", "Assigned At"])
    assignments = db.query(AlterAssignment).join(LeaveRequest).order_by(LeaveRequest.date.desc()).all()
    for assignment in assignments:
        leave = assignment.leave_request
        slot = db.query(TimetableSlot).filter(TimetableSlot.teacher_id == leave.teacher_id, TimetableSlot.day_order == leave.day_order, TimetableSlot.period_number == leave.period_number).first()
        ws.append([leave.id, str(leave.date), f"{slot.class_.name} - {slot.class_.section}" if slot else None, leave.teacher.name, leave.teacher.department, assignment.substitute.name, assignment.substitute.department, leave.teacher.department_id != assignment.substitute.department_id, leave.day_order, leave.period_number, assignment.assignment_type.value, str(assignment.assigned_at)])

    ws = _sheet(wb, "Export Metadata", ["Field", "Value"])
    ws.append(["Generated at (UTC)", datetime.now(timezone.utc).isoformat()])
    ws.append(["Generated by", generated_by])
    ws.append(["Scope", "Institution-wide master export"])
    stream = BytesIO()
    wb.save(stream)
    return stream.getvalue()
