-- Migration 007: Performance indexes for high-frequency query paths
-- Generated by FAFLOW Enterprise QA Audit 2026-07-24
-- These indexes cover the most common filter/join patterns observed in
-- leave_service, credit_service, substitution_service, and notification queries.
-- All are created with IF NOT EXISTS — safe to apply to any existing installation.

-- Leave requests (most heavily queried table in leave workflows)
CREATE INDEX IF NOT EXISTS idx_leave_requests_teacher_id      ON leave_requests(teacher_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_date            ON leave_requests(date);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status          ON leave_requests(status);
CREATE INDEX IF NOT EXISTS idx_leave_requests_teacher_date    ON leave_requests(teacher_id, date);
CREATE INDEX IF NOT EXISTS idx_leave_requests_day_order       ON leave_requests(day_order);

-- Alter assignments (substitute lookup)
CREATE INDEX IF NOT EXISTS idx_alter_assignments_leave_id     ON alter_assignments(leave_request_id);
CREATE INDEX IF NOT EXISTS idx_alter_assignments_substitute   ON alter_assignments(substitute_teacher_id);

-- Credit transactions (credit report and balance queries)
CREATE INDEX IF NOT EXISTS idx_credit_transactions_teacher_id ON credit_transactions(teacher_id);
CREATE INDEX IF NOT EXISTS idx_credit_transactions_created_at ON credit_transactions(created_at DESC);

-- Timetable slots (conflict checks and slot lookup)
CREATE INDEX IF NOT EXISTS idx_timetable_slots_teacher_id     ON timetable_slots(teacher_id);
CREATE INDEX IF NOT EXISTS idx_timetable_slots_class_id       ON timetable_slots(class_id);
CREATE INDEX IF NOT EXISTS idx_timetable_slots_day_period     ON timetable_slots(day_order, period_number);
CREATE INDEX IF NOT EXISTS idx_timetable_slots_teacher_day_p  ON timetable_slots(teacher_id, day_order, period_number);

-- Notifications (unread count polling — most frequent query)
CREATE INDEX IF NOT EXISTS idx_notifications_user_read        ON notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_user_created     ON notifications(user_id, created_at DESC);

-- Users (department filtering)
CREATE INDEX IF NOT EXISTS idx_users_department_id            ON users(department_id);
CREATE INDEX IF NOT EXISTS idx_users_role                     ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_is_active                ON users(is_active);

-- Calendar days (day order resolution — called on every leave submission)
CREATE INDEX IF NOT EXISTS idx_calendar_days_date             ON calendar_days(date);
CREATE INDEX IF NOT EXISTS idx_calendar_days_day_type         ON calendar_days(day_type);
CREATE INDEX IF NOT EXISTS idx_calendar_days_day_order        ON calendar_days(day_order);

-- Audit logs
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor               ON audit_logs(actor_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_department          ON audit_logs(department_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at          ON audit_logs(created_at DESC);
